version: '3'

services:
  hardhat:
    build: .
    container_name: polygon-hardhat
    working_dir: /app
    environment:
      - NETWORK=mumbai
      - PRIVATE_KEY=${PRIVATE_KEY}
      - INFURA_API_KEY=${INFURA_API_KEY}
    volumes:
      - .:/app
    tty: true